parameters:
#    class_central_elastic_search.example.class: ClassCentral\ElasticSearchBundle\Example

services:
#    class_central_elastic_search.example:
#        class: %class_central_elastic_search.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
